[package]
name = "gat-borrow"
version = "0.1.0"
edition = "2024"
description = "Rewrite of the borrow module using GATs"
license = "GPL-3.0-or-later"
repository = "https://github.com/sautibara/gat-borrow"
readme = "README.md"

[dependencies]
gat-borrow-derive = { version = "0.1.0", path = "../gat-borrow-derive/" }

[lints]
workspace = true
