[package]
name = "gat-borrow-derive"
version = "0.1.1"
edition = "2024"
description = "Macros for the gat-borrow crate"
license = "GPL-3.0-or-later"
repository = "https://github.com/sautibara/gat-borrow"
readme = "README.md"

[dependencies]
quote = "1.0.35"
syn = { version = "2.0.85", features = ["full", "fold"] }
proc-macro2 = "1.0.79"

[lib]
proc-macro = true

[lints]
workspace = true
